apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # Type of service; can be ClusterIP, NodePort, or LoadBalancer
  selector:
    app: nginx  # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 80 # Port on which the container is listening
